# Generated by Django 3.2.6 on 2021-08-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=128, null=True, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.TextField(max_length=6000, null=True, verbose_name='자기소개'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='0000', max_length=64, verbose_name='비밀번호'),
        ),
    ]
